import { useState } from 'react';
import { NavLink } from 'react-router-dom';

const links = [['/', 'Home'], ['/services', 'Services'], ['/doctors', 'Doctors'], ['/about', 'Our approach']];

const Navbar = () => {
  const [open, setOpen] = useState(false);
  const navClass = ({ isActive }) => `text-sm font-medium transition ${isActive ? 'text-primary-700' : 'text-text-secondary hover:text-primary-800'}`;
  return <header className="sticky top-0 z-50 border-b border-primary-100/70 bg-white/90 backdrop-blur-md"><nav className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8"><NavLink to="/" className="flex items-center gap-3" aria-label="MediCare+ home"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary-700 text-white shadow-sm"><svg className="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.3"><path d="M12 5v14M5 12h14" /></svg></span><span><span className="block text-lg font-bold leading-none tracking-tight text-primary-900">MediCare<span className="text-primary-600">+</span></span><span className="mt-1 block text-[10px] font-semibold uppercase tracking-[.16em] text-text-secondary">Better care, simply</span></span></NavLink><div className="hidden items-center gap-7 md:flex">{links.map(([to, label]) => <NavLink key={to} to={to} end={to === '/'} className={navClass}>{label}</NavLink>)}</div><div className="flex items-center gap-2"><NavLink to="/contact" className="hidden rounded-lg bg-primary-700 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-primary-800 sm:inline-flex">Book appointment</NavLink><button type="button" onClick={() => setOpen(!open)} aria-expanded={open} aria-label="Toggle navigation" className="rounded-lg p-2 text-primary-800 hover:bg-primary-50 md:hidden"><svg className="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M4 7h16M4 12h16M4 17h16" /></svg></button></div></nav>{open && <div className="border-t border-primary-100 bg-white px-4 py-4 md:hidden"><div className="mx-auto flex max-w-7xl flex-col gap-1">{links.map(([to, label]) => <NavLink key={to} to={to} end={to === '/'} onClick={() => setOpen(false)} className={({isActive}) => `rounded-lg px-3 py-2.5 text-sm font-medium ${isActive ? 'bg-primary-50 text-primary-700' : 'text-text-secondary'}`}>{label}</NavLink>)}<NavLink to="/contact" onClick={() => setOpen(false)} className="mt-2 rounded-lg bg-primary-700 px-3 py-2.5 text-center text-sm font-semibold text-white">Book appointment</NavLink></div></div>}</header>;
};

export default Navbar;
